### ISSUE TITLE
Support HTTP proxy

### ISSUE THREAD

**Issue by JensRantil** [Yubico/yubico-pam#103]
Feature request: Support HTTP proxy and not just SOCKS\* proxy.

Any specific reason why this isn't supported?

**Comment by klali** [comment]
My understanding of the proxy parameter is that it accepts any type of proxy. That parameter is passed directly to curl as CURLOPT_PROXY, see: https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by JensRantil** [comment]
@klali I see! In that case https://github.com/Yubico/yubico-pam#configuration (`proxy`) and https://developers.yubico.com/yubico-pam/ should probably be updated to state that the property also supports `http://`. Am I correct?

**Comment by SkullKill** [comment]
on centos 7,

proxy=http://IpOfSquidServer:3128

works . but had to create a custom selinux rule for sshd to use tcp port 3128
(posting this just in case someone is having issues getting this to work )

**Comment by JensRantil** [comment]
Yes, we've also verified it to work. Closing this and will create a separate issue for documenting the support.
