### ISSUE TITLE
Config file for PAM

### ISSUE THREAD

**Issue by mhalano** [Yubico/yubico-pam#105]
Mostly of PAM modules use a file inside /usr/share/pam-config/ to enable configuration using the command pam-auth-update. yubico-pam should have this file.

**Comment by klali** [comment]
The debian packaging of yubico-pam includes such a file (at https://github.com/Yubico/yubico-pam-dpkg/blob/master/debian/pam-auth-update)

Maybe this would make more sense in the base packaging, not sure how standard that location is with different distros.

**Comment by mhalano** [comment]
@klali The file exists on /usr/share/libpam-yubico/pam-auth-update.template, but should be on directory /usr/share/pam-config/.

**Comment by klali** [comment]
This happens in the postinst: https://github.com/Yubico/yubico-pam-dpkg/blob/master/debian/libpam-yubico.postinst which works for me on xenial.

**Comment by mhalano** [comment]
@klali works on Xenial indeed, I could fill a bug on yubico-pam-dpkg to put the file where belong instead of use a postinst script. What you think?

**Comment by klali** [comment]
The reason it's built with the postscript is that it fills it in with values from debconf. I'm unsure if there's a better way to fill those values in.
