### ISSUE TITLE
How to uninstall (Mac OS X)

### ISSUE THREAD

**Issue by MatzFan** [Yubico/yubico-pam#107]
Hi

I have installed the PAM (v2.23) via the package installer on the Downloads section of your [website](https://developers.yubico.com/yubico-pam/Releases/pam_yubico-2.23.pkg). It does not appear to include an uninstaller, so I'd be grateful for instructions on how to cleanly remove the tool. It looks like I ned to remove the following:
```bash
/usr/local/lib/libjson-c.2.dylib
/usr/local/lib/libykclient.3.dylib
/usr/local/lib/libykpers-1.1.dylib
/usr/local/lib/libyubikey.0.dylib
```
and:-

`/usr/local/lib/security/pam_yubico.so`

and the executable:-

`/usr/local/bin/ykpamcfg`

Is that all?

Thanks in advance

Mac OS X 10.11.6

**Comment by klali** [comment]
Installed files can be listed with:
 $ pkgutil --files com.yubico.pam_yubico
After they've been removed the package can be forgotten with:
 $ pkgutil --forget com.yubico.pam_yubico

Unfortunately pkgutil doesn't provide an uninstall, maybe we should provide that.

**Comment by MatzFan** [comment]
Great, thanks @klali - an uninstaller would be ideal.
