### ISSUE TITLE
./configure: line 13427: syntax error near unexpected token `YKPERS,'

### ISSUE THREAD

**Issue by chmmeng** [Yubico/yubico-pam#109]
when I compile the yubico-pam get the error below:
./configure: line 13427: syntax error near unexpected token `YKPERS,'
./configure: line 13427: `  PKG_CHECK_MODULES(YKPERS, ykpers-1 >= 1.8.0);'

**Comment by klali** [comment]
That should not be left in the configure script after autotools has processed configure.ac.

On what type of system is this?
Do you have pkg-config installed?
Did you run autoreconf --install to prepare the build?

**Comment by chmmeng** [comment]
Thanks for the reply;

1.centos 6.5

2.After install pkg-config-0.18  then "autoreconf --install "  get the new error: 

[root@kms pkgconfig]# export YKPERS_CFLAGS="-I/root/usr/include -pthread"
[root@kms pkgconfig]# export YKPERS_LIBS="-L/root/usr/lib -lykpers-1"
[root@kms pkgconfig]# export PKG_CONFIG_PATH=/root/usr/lib/pkgconfig
[root@kms pkgconfig]# export PATH=/root/usr/bin:$PATH
[root@kms pkgconfig]# pkg-config --cflags --libs ykpers-1
-pthread -I/root/usr/include/  -L/root/usr/lib -lykpers-1  

[root@kms ~]# cd yubico-pam-2.23
[root@kms yubico-pam-2.23]# ./configure --prefix=/root/usr
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking security/pam_appl.h usability... yes
checking security/pam_appl.h presence... yes
checking for security/pam_appl.h... yes
checking for security/pam_modules.h... yes
checking for security/_pam_macros.h... yes
checking for security/pam_modutil.h... yes
checking for pam_start in -lpam... yes
checking for library containing pam_modutil_drop_priv... no
checking for ldap_init in -lldap... no
configure: WARNING: libldap not found, will not be compiled (--without-ldap to disable ldap support)
checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for libykclient... yes
checking how to link with libykclient... -lykclient
checking for libyubikey... yes
checking how to link with libyubikey... -lyubikey
checking pkg-config is at least version 0.9.0... yes
checking for YKPERS... configure: error: in `/root/yubico-pam-2.23':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively you may set the YKPERS_CFLAGS and YKPERS_LIBS environment variables
to avoid the need to call pkg-config.  See the pkg-config man page for
more details.

To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
See `config.log' for more details.
[root@kms yubico-pam-2.23]# cd /root/usr/lib/pkgconfig/
[root@kms pkgconfig]# ls
ykpers-1.pc
[root@kms pkgconfig]# cat ykpers-1.pc 
prefix=/root/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Libykpers
Description: Personalization library for the YubiKey
URL: http://www.yubico.com/
Version: 1.18.0
Libs: -L${libdir} -lykpers-1 
Cflags: -I${includedir}/ -pthread

[root@kms pkgconfig]# cd /root/usr/bin
[root@kms bin]# ls
modhex  pkg-config  ykchalresp  ykclient  ykgenerate  ykinfo  ykparse  ykpersonalize
[root@kms bin]# pkg-config --version
0.18

how to solved the error,thanks. Is there any special request for the pkg-config version?

configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

**Comment by klali** [comment]
So a step forwards at least.

Your ykpers-1.pc file looks odd, the include path should be /root/usr/include/ykpers-1, I wonder where that got lost?

The error looks odd as well, there shouldn't be room for pkg-config to fail if YKPERS_CFLAGS and YKPERS_LIBS are both set.
If you run the official packages (from https://developers.yubico.com/yubico-pam/Releases/) you shouldn't need to re-run the autotools part so we can eliminate that as the possible error.

**Comment by chmmeng** [comment]
Thanks！ the official packages can compile smoothly!
