### ISSUE TITLE
Using mode=challenge-response with ssh

### ISSUE THREAD

**Issue by ruimarinho** [Yubico/yubico-pam#111]
Is it possible to use the offline `challenge-response` mode for ssh? I get a module not found when sshd attempts to load the `libpam_yubico.so`.

Also, I'm getting a segmentation fault when enabling authentication on Ubuntu (14.04) using `2.24-1~ppa1~trusty1` and running simply `sudo su`.

**Comment by klali** [comment]
Not possible to use challenge-response mode for ssh, the yubikey would have to be in place in the server.

The segfault is very interesting, I'm not able to directly reproduce that.
How is pam configured?
Can you capture a debug log? (turn on debug and debug_file pointing at an empty file)

**Comment by ruimarinho** [comment]
I will look into that. I have debug (including debug_file) enabled but there's no output there, so I'll confirm if I'm missing something. pam is configured on common-auth with `mode=challenge-response`, so that might explain it.

So, regarding ssh, is it possible to have offline validation at all?

**Comment by klali** [comment]
The file pointed at by debug_file must exist for it to be written to. What's the complete line you use in common-auth ?

No support for offline validation with ssh in this pam module.

**Comment by ruimarinho** [comment]
@klali, I've tried to replicate this over and over again, with and without docker-in-docker, which was the initial setup that had the segmentation fault originate, and I haven't succeeded. I even had a core dump to share with you, since I was not getting any logs at all. 

The good news is that I can't make it crash anymore. The bad news is that I don't know what fixed it and that is driving me nuts :-). Could it have been an exclusive lock caused by another running app?

**Comment by klali** [comment]
Glad that it's fixed.
The module shouldn't be crashing under any circumstances, if you have a backtrace I'll look at it.

**Comment by ira-lb** [comment]
Just my 2c to see that I have understood this:
the HMAC chalresp method requires the USB path to the key, so it needs to be physically connected to the machine running pam module, but the client method only looks at the string, which is then authenticated online with a yubico auth server. so far correct?

So, if I can run my own server, give the url as localhost to the pam module, I could use the yubikey=OTP method with a local auth server, which is practically an "offline" login, no?
