### ISSUE TITLE
USB error: kIOReturnSuccess on macOS Sierra 10.12.3

### ISSUE THREAD

**Issue by andrewLarsson** [Yubico/yubico-pam#115]
I updated to macOS 10.12.3 from I believe 10.12.2 (not 100% sure, though). And I am no longer able to use my Yubikey for login on my MacBook Pro. Luckily I was able to disable it just fine so I at least can use my MacBook. But I've tried fixing it so I can use my Yubikey again and I've had no luck. I've updated to the latest `pam_yubico.so` (v2.23) and I've disabled Yubikey PIV mode just to make sure macOS wasn't conflicting the PAM and the PIV. I have my Yubikey configured for challenge-response PAM login. I have "Secure Keyboard Entry" disabled in my Terminal. One weird thing I've noticed is the green light on the Yubikey is always on now. Also, it will work for a few minutes right after a reboot, and then it will stop working and start producing errors.

Any ideas?

My output for `ykinfo` is as follows:
```
Andrew$ ./ykinfo -a
USB error: kIOReturnSuccess
```
and
```
Andrew$ sudo ./ykinfo -a
serial: 5010478
serial_hex: 4c742e
serial_modhex: frifdu
version: 4.3.3
touch_level: 519
programming_sequence: 3
slot1_status: 1
slot2_status: 1
vendor_id: 1050
product_id: 407
```

My `system.log` has the following entries when I try to log in:
```
Feb 10 16:29:41 Protégé loginwindow[113]: Challenge response failed: Stale NFS file handle
Feb 10 16:29:41 Protégé loginwindow[113]: USB error: kIOReturnSuccess
Feb 10 16:29:41 Protégé loginwindow[113]: Challenge response failed: Operation not permitted
Feb 10 16:29:41 Protégé loginwindow[113]: USB error: kIOReturnSuccess
```

**Comment by thorduri** [comment]
Hi,

If you can still reproduce this, it would be helpful to see the output with the `debug` parameter
set in your pam configuration.

**Comment by andrewLarsson** [comment]
I am unable to reproduce this on macOS Sierra 10.12.6. The only changes to my system were regular macOS updates (I did not update anything Yubikey related).

**Comment by Danrancan** [comment]
Hi, I was wondering if you might reopen this issue. I am currently reproducing the exact same problem on Mac OS Mojave 10.14.6 (18G2022), when trying to create a yubikey logon file.

`~ boo$ ykpamcfg -2
USB error: kIOReturnSuccess`
