### ISSUE TITLE
CentOS 7 Update breaks logins

### ISSUE THREAD

**Issue by knobdy** [Yubico/yubico-pam#120]
```
Mar 28 18:37:24 hostname cw: PAM unable to dlopen(/usr/lib64/security/pam_yubico.so): /lib64/libnssutil3.so: undefined symbol: PR_GetEnvSecure
Mar 28 18:37:24 hostname cw: PAM adding faulty module: /usr/lib64/security/pam_yubico.so
```
After installing the latest pam_yubico (or not) and then updating the system I get these errors attempting to use it.

**Comment by klali** [comment]
That looks like /lib64/libnssutil3.so is sad, not pam_yubico. You might have issues with a mix of libraries and ABI incompatibilities from your upgrade.

**Comment by knobdy** [comment]
This isn't the only PAM module being used but it is the only one complaining. Can you give me a hint as to where to look and how? The updates to the OS (and I would guess this is true for all like - RHEL - systems) break all versions of this module that I've tried.

**Comment by thorduri** [comment]
@knobdy From what to what did you upgrade ?

Can you provide the contents of `/etc/os-release` and are you perchance installing from source ?

If not, could you list which packages you have installed related to pam ?

**Comment by knobdy** [comment]
I'm just doing the standard update of all packages. Should add that I have since gotten this to work - sorta - with _yum downgrade nss*_.

Contents of /etc/os-relase:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
