### ISSUE TITLE
Api.yubico.com is down for everyone

### ISSUE THREAD

**Issue by cryptofuture** [Yubico/yubico-pam#123]
Sorry, for writing it here, but I didn't found any support beside sales person and mostly deadly forum (where I need to register first)  
Basically there was some error in old yubico-pam build, and thats why  `urllist=https://api.yubico.com/wsapi/2.0/verify` end in my configurations.
http://www.isitdownrightnow.com/api.yubico.com.html says Api.yubico.com is down for everyone, and i can't open it too right now.
Surely removing `urllist=https://api.yubico.com/wsapi/2.0/verify`helps, but problem is I have no physical access to all servers, and I don't want to stop them. 
Could you please poke, someone from yubico to fix it. And also make some warning or announcement to users with suggestion to remove this line from configurations.

**Comment by dainnilsson** [comment]
Just a quick FYI that api.yubico.com is up and running again.

**Comment by cryptofuture** [comment]
Yea, great! But seriously, you should think about announcement or warning about  how bad is to use `urllist` with single tolerance point. Beside I think using just `https://api.yubico.com/wsapi/2.0/verify` was quite common in docs some time ago.
