### ISSUE TITLE
Error calling `pam_modutil_drop_priv` on Amazon Linux using pam_yubico from EPEL

### ISSUE THREAD

**Issue by alsmola** [Yubico/yubico-pam#126]
I'm trying to get SSH 2FA with Yubikey working on Amazon Linux. I've gotten it working when compiling directly from source, but when installing the package, using the Fedora/EPEL repository, with an otherwise similar configuration I get the following error in my sshd logs when the SSHing user enters the Yubikey text:

`pam_yubico(sshd:auth): pam_modutil_drop_priv: called without room for supplementary groups`

It's very possible that this isn't an issue with this PAM module, but wanted to report it nonetheless.

**Comment by alsmola** [comment]
I wrote up a quick walkthrough of how I compiled it on Amazon Linux here: https://gist.github.com/alsmola/21317491d7f8c4dc73b0b70ed6f3bf5a

**Comment by klali** [comment]
Odd, this shouldn't happen, the supplementary groups should be allocated when the structure is defined with PAM_MODUTIL_DEF_PRIVS.
Could you try running this with debug enabled and send the output here?

**Comment by alsmola** [comment]
I just tried to repro this from scratch, and was unable to. I successfully enabled 2FA using the EPEL package. I updated my gist accordingly, with instructions for installing the package and compiling from source.

I was wondering if you wanted to add something for Amazon Linux [in your docs](https://www.yubico.com/solutions/#computer-login)? Happy to type up a quick blog post.
