### ISSUE TITLE
Ubuntu 16.04 Challenge-Response Segfault

### ISSUE THREAD

**Issue by elbaro** [Yubico/yubico-pam#128]
```
sudo add-apt-repository ppa:yubico/stable
sudo apt-get update
sudo apt-get install libpam-yubico
```
```
Package: libpam-yubico
Version: 2.24-1~ppa1~xenial1
```
and added `auth sufficient pam_yubico.so mode=challenge-response` in `common-auth`

Then running `sudo echo 123` segfaults. I tested on three Ubuntu 16.04 machines and all crashed. 
Building `libpam-yubico` from git (also building `yubikey-personalization` & `yubico-c-client`) doesn't crash anymore.
Can you update the binary in the ppa?

**Comment by klali** [comment]
I'm not getting crashes with 2.24 from ppa on 16.04 with same configuration.

Do you have that as the first line in common-auth?
Can you enable debug and send the output here?

(Might still be a good idea to release 2.25, but I'd like to track this down)

**Comment by elbaro** [comment]
Found why. I need `libykclient3 >= 2.15` but `libpam-yubico 2.24~1` only requires `libykclient >= 2.12`.

1. Run `sudo apt install libpam-yubico` which installs 2.20-1 with libykclient 2.14-1.
2. Add ppa, update
3. Run `sudo apt install libpam-yubico` which upgrades to 2.25-1 but leaves libykclient 2.14-1.
4. `sudo` crashes.

```
$ ldd /lib/security/pam_yubico.so 
/lib/security/pam_yubico.so: /usr/lib/x86_64-linux-gnu/libykclient.so.3: version `YKCLIENT_2.15' not found (required by /lib/security/pam_yubico.so)
```

**Comment by klali** [comment]
Good catch. I'm pushing updated builds to the ppa. Thanks!
