### ISSUE TITLE
New release with nullok support

### ISSUE THREAD

**Issue by kbabioch** [Yubico/yubico-pam#134]
nullok support has been added in the past with 7b6aad719a099bc28448fed9c9304563d6665f87, and has been improved since then (1d62bec277c2792618427ffe4f192ef6b815d545, 8db623de5dfe81c4b62379fcf91e7908342afa10, b7910915023568a6e4ba38d1a6198c4c8bec09fa). However, there hasn't been a release for 1,5 years and this feature is not yet included.

**Comment by klali** [comment]
2.25 has been released.
