### ISSUE TITLE
Ubuntu 18.04.1 LTS - YubiKey Firmware version: 5.1.1 - challenge to slot 2 Yubikey core error: timeout

### ISSUE THREAD

**Issue by ricebx** [Yubico/yubico-pam#171]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

+++++++++++++++++++++++++++++++++++++++++++++++++++++++

ykpamcfg -2 -v
[../util.c:check_firmware_version(212)] YubiKey Firmware version: 5.1.1

Sending 63 bytes HMAC challenge to slot 2
Yubikey core error: timeout

![screenshot from 2018-11-09 11-22-45](https://user-images.githubusercontent.com/43169288/48241571-82cfc980-e412-11e8-8b50-bc2437d109a8.png)

**Comment by klali** [comment]
You need to use the "HMAC-SHA1" mode of challenge response, not the "Yubico OTP" kind.

**Comment by ricebx** [comment]
I used the "HMAC-SHA1" mode of challenge-response, tried different options and still cant.

![screenshot from 2018-11-14 11-48-22](https://user-images.githubusercontent.com/43169288/48459423-ff90e800-e804-11e8-9db4-60a3e984caf1.png)

![screenshot from 2018-11-14 11-46-28](https://user-images.githubusercontent.com/43169288/48459459-31a24a00-e805-11e8-9a8a-0d98c8dc4d48.png)
