### ISSUE TITLE
yubikey fails intermediately 

### ISSUE THREAD

**Issue by mxcheng2011** [Yubico/yubico-pam#176]
Since yesterday, our yubikey fails intermediately with error message.

`debug: pam_yubico.c:1154 (pam_sm_authenticate): Token is associated to the user. Validating the OTP...

debug: pam_yubico.c:1156 (pam_sm_authenticate): ykclient return value (101): Could not parse server response

debug: pam_yubico.c:1157 (pam_sm_authenticate): ykclient url used: https://api.yubico.com/wsapi/2.0/verify?xxxxx`

Is this a problem of our server or the yubikey cloud service?

**Comment by klali** [comment]
This is probably due to https://status.yubico.com/2018/11/26/deprecating-yubicloud-v1-protocol-plain-text-requests-and-old-tls-versions/

What distribution are you running? What version of libcurl is installed?

**Comment by wamuir** [comment]
@mxcheng2011 I was able to resolve this issue by passing the yubico endpoints into pam via the urllist parameter.  Example:

`auth            sufficient      /usr/local/lib/security/pam_yubico.so id=16 urllist=https://api.yubico.com/wsapi/2.0/verify`

The endpoints are provided within the link given by @klali and are semicolon separated (see [https://developers.yubico.com/yubico-pam/Manuals/pam_yubico.8.html](https://developers.yubico.com/yubico-pam/Manuals/pam_yubico.8.html))

**Comment by mxcheng2011** [comment]
A yum update solves the problem.  Thank you!

**Comment by mxcheng2011** [comment]
William, thanks for your comment. I tried it by specifying a particular api server, but it didn't help. Then I run a yum update for all the rpms, which solved the problem.
