### ISSUE TITLE
No prompt with sudo

### ISSUE THREAD

**Issue by abstractalchemist** [Yubico/yubico-pam#177]
I've tried to setup yubikey for two-factor for sudo using challenge-response in my second slot.  But when I run sudo, there's no prompt asking me for a yubikey challenge.  But if I then press my yubikey, it then correctly prompts me for my password.  Is there a way to configure pam_yubico to display a prompt?  Using Fedora 29.

**Comment by klali** [comment]
There's only prompting for the OTP mode, not challenge response.
