### ISSUE TITLE
Unintentional password logging 

### ISSUE THREAD

**Issue by syutbai** [Yubico/yubico-pam#184]
Hi,

We ran into a problem where a user types username and password and submits without the OTP.  This resulted with the password being logged in cleartext in the pam_yubico.log during the OTP parsing process:
```
OTP: <password> ID: <password>
```

We found it unacceptable for the password to be output into the log in cleartext, even though this was the result of a user mistake.  It is a mistake that may be very common for a user to type in password without submitting the OTP along with it.  

Solution Suggestion: 
* Remove line 1178 logging and move it to after OTP ID has been validated.  This way the log always outputs a valid OTP and not an accidental password:  
<pre>
# git diff
diff --git a/pam_yubico.c b/pam_yubico.c
index 2c6c5d9..c33027d 100644
--- a/pam_yubico.c
+++ b/pam_yubico.c
@@ -1175,8 +1175,6 @@ pam_sm_authenticate (pam_handle_t * pamh,
   /* Copy only public ID into otp_id. Destination buffer is zeroed. */
   strncpy (otp_id, password + skip_bytes, cfg->token_id_length);
 
-  DBG ("OTP: %s ID: %s ", otp, otp_id);
-
   /* user entered their system password followed by generated OTP? */
   if (password_len > TOKEN_OTP_LEN + cfg->token_id_length)
     {
@@ -1211,6 +1209,7 @@ pam_sm_authenticate (pam_handle_t * pamh,
   switch(valid_token)
     {
     case AUTH_FOUND:
+      DBG ("OTP: %s ID: %s ", otp, otp_id);
       DBG ("Token is associated to the user. Validating the OTP...");
       rc = ykclient_request (ykc, otp);
       DBG ("ykclient return value (%d): %s", rc, ykclient_strerror (rc));
</pre>

**Comment by nevun** [comment]
This has now been fixed, thank you for the report.
