### ISSUE TITLE
Cannot login with nullok if configured at user level and user's authfile does not exist

### ISSUE THREAD

**Issue by zypA13510** [Yubico/yubico-pam#194]
When [using per-user authfile](https://github.com/Yubico/yubico-pam/blob/fcfcba6c2fd0fd7782a547becfc00d99f40bfb15/pam_yubico.c#L176) to [perform the check](https://github.com/Yubico/yubico-pam/blob/fcfcba6c2fd0fd7782a547becfc00d99f40bfb15/pam_yubico.c#L209), and [the file for that user does not exist](https://github.com/Yubico/yubico-pam/blob/fcfcba6c2fd0fd7782a547becfc00d99f40bfb15/util.c#L125), pam_yubico will [return `PAM_AUTHINFO_UNAVAIL`](https://github.com/Yubico/yubico-pam/blob/fcfcba6c2fd0fd7782a547becfc00d99f40bfb15/pam_yubico.c#L1105) even if `nullok` is set, which is imo probably not what the users expect. Instead, I would expect that `PAM_IGNORE` is returned like what happened when using a central authfile and the username is not found in that file.

**Comment by klali** [comment]
Yes, this should get `PAM_IGNORE` in the `nullok` case. I'm not sure the best is to change the failure to open file to return `AUTH_NO_TOKENS`, maybe `AUTH_ERROR` should get `PAM_IGNORE` if `nullok` is set instead. I'll ponder this, please reply here if you have preferences/opinions.

**Comment by zypA13510** [comment]
Partly the reason why I did not open a PR. For me both are OK. But I think maybe you can try to take a look at other PAM modules, especially those built-in modules, and determine if they return ERROR or IGNORE when nullok is set?
(I'm sorry but this is the first time I have configured a PAM module so not really my expertise.)

**Comment by klali** [comment]
I've just pushed a branch with a potential fix for this, need to make sure we're not missing a case here, but please try it out.

**Comment by zypA13510** [comment]
Yes, now it returns ignore when nullok is set and the file is not there. Tested on CentOS 7.

Btw, I'm also working on a CircleCI script on my fork that would allow PR and commits to have artifacts (rpm/deb/so) published, which Travis does not provide. I think it would be easier to manually test a patch with a package than building from scratch. It's still a work in progress, but if you're interested in merging it, I'd keep working on it.

**Comment by klali** [comment]
Great.

I don't think moving to CirculCI would be interesting now, Yubico has a bit of a mix right now but we're looking at how to consolidate our CI needs best. Providing useful binaries out of the CI system sounds like a good thing to have.

**Comment by zypA13510** [comment]
Ok, thanks for the info.
