### ISSUE TITLE
Not truly open-source

### ISSUE THREAD

**Issue by reesericci** [Yubico/yubico-pam#212]
The license you people are using has a copyright notice and is therefore not truly open-source and not free as in freedom. I see this as a serious issue.

**Comment by dainnilsson** [comment]
Hi! This project uses the OSI approved "BSD 2 clause" license (https://opensource.org/licenses/BSD-2-Clause).

Most open source software contains a notice of copyright, which is something inherently granted to the creator of said software (you create it, you own it). The reason we have open source licenses is to grant permission to others to use the code, sometimes with restrictions. However, this does not change the copyright, and in fact in some jurisdictions this right cannot be waived. Work that does not have a copyright holder is considered "public domain", which is different from being open source.

Please see the following link for more information: https://opensource.org/faq#public-domain

**Comment by reesericci** [comment]
Thanks for the clarification
