### ISSUE TITLE
Can I use NFC?

### ISSUE THREAD

**Issue by ai** [Yubico/yubico-pam#215]
I want to make a laptop unlocking faster. I will buy an external NFC reader. It will be very good if I can just touch my NFC reader to unlock my laptop.

Can I do it right now with `yubico-pam`?

**Comment by klali** [comment]
This project can't use NFC, it can only use USB HID for communication.

**Comment by crosser** [comment]
@ai you can use [this PAM module](https://github.com/crosser/pam_pcsc_cr) with NFC.

Note that just touching yubikey to the reader won't be enough, such functionality would require modifications in the display manager greeter(s).
