### ISSUE TITLE
Abnormal time delay on pam_yubico on CentOS 7

### ISSUE THREAD

**Issue by andyneff** [Yubico/yubico-pam#218]
I've set up pam yubico on dozens of Fedora and Centos 7 machines, but on my latest CentOS 7 machine, I have an unexplained time delay when doing any authentications, including but not limited to:

- `ssh`
- `sudo`
- `su`

There is a delay between 30 and 60 seconds when in, before I ever see "YubiKey for `user':" (I haven't measured exactly how long).

## How pam_yubico.so is configured

- Installed using: `yum install pam_yubico-2.26-1.el7.x86_64`
- This is the line in my pam.d file:

`auth sufficient pam_yubico.so id=*id redacted* key=*key redacted* urllist=https://yubikeyserver:22112/wsapi/2.0/verify ldap_uri=ldap://adserver:389/ ldapdn=cn=Users,dc=company,dc=com yubi_attr=yubiKeyId ldap_bind_user=cn=Yubico,cn=Users,dc=company,dc=com ldap_bind_password=*password redacted* ldap_filter=sAMAccountName=%u`

I use the following configurations rules to keep SELinux happy:

- `setsebool -P authlogin_yubikey 1`
- `setsebool -P authlogin_nsswitch_use_ldap 1`
- `semanage port -a -t http_port_t -p tcp 22112`

## What I've looked at

- No errors show up in `/var/log/messages`
- No failures show up in `/var/log/audit/audit.log`
- If I add `debug debug_file=/tmp/yubi`, nothing shows up in `/tmp/yubi` until AFTER the 30+ second time delay is done.

I'm not able to determine what is causing this time delay or any symptoms to go with it, only that it affects everything pam related, and if I comment out the pam_yubico line, the time delay goes away.

**Comment by nevun** [comment]
Sounds like a typical DNS issue. Can you do `tcpdump -l -n -i <interface> port 53` during a login attempt and see if there are any lookups?

**Comment by andyneff** [comment]
@nevun you are completely correct! (Due to a pandemic reasons) the computer itself was never added to the DNS table in AD.

So the problem was the computer (named `conway`) didn't know who `conway` was. It can only rely on DNS to tell it that, and well on VPN it didn't know. Off VPN it wouldn't know who `yubikeyserver` is, but that's ok.

Thanks for the help!
