### ISSUE TITLE
RFC4515 not implemented

### ISSUE THREAD

**Issue by 7ippy** [Yubico/yubico-pam#223]
# Program flow

- In [pam_yubico.c:1018](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L1018) the name of the user is read out via pam_get_user(...) and saved in the variable user.

- In [pam_yubico.c:1134](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L1134) or [pam_yubico.c:1258](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L1258) the variable user is passed to the function authorize_user_token_ldap(...) together with an instance of the cfg structure.

- In [pam_yubico.c:394](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L394) the variable user is passed to the function filter_printf(...) together with the variable ldap_filter from the instance of the cfg structure.

- In [util.c:785](https://github.com/Yubico/yubico-pam/blob/2.27/util.c#L785) the variable user is passed to the function filter_result_len(...) together with the variable filter.

- The position of the string "%u" in the variable filter is determined in [util.c:756](https://github.com/Yubico/yubico-pam/blob/2.27/util.c#L756).

- In [util.c:772](https://github.com/Yubico/yubico-pam/blob/2.27/util.c#L772) the position of the string "%u" is replaced with the content of the variable user, thus creating the final LDAP filter.

- In [pam_yubico.c:403](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L403) the final LDAP filter is passed as filter to the function ldap_search_ext_s(...). 

# RFC 4515

RFC 4515 defines the syntax of LDAP search filters. The syntax is defined in Chapter 3 on page 3f.

The "\<valueencoding\> rule" specifies that the characters "*", "(", ")", "\\", and NUL must be replaced by their hexadecimal representation and a preceding ESC ("\\"). 

> _[RFC 4515, Chapter 3](https://www.rfc-editor.org/rfc/rfc4515.html#section-3), Page 4:_
> The \<valueencoding\> rule ensures that the entire filter string is a valid UTF-8 string and provides that the octets that represent the ASCII characters "*" (ASCII 0x2a), "(" (ASCII 0x28), ")" (ASCII 0x29), "\\" (ASCII 0x5c), and NUL (ASCII 0x00) are represented as a backslash "\\" (ASCII 0x5c) followed by the two hexadecimal digits representing the value of the encoded octet.

# Review

According to the program flow, the "\<value coding\> rule" is not applied to the user name that has been read out because no substitution of the characters "*", "(", ")", "\\", and NUL is taking place.

As a result, the final LDAP filter is incorrect and the LDAP search fails if the user name contains one of the characters "*", "(", ")", "\\" or NUL. 

# Situation

In my case, the DEBIAN operating system version 10.9 is installed on a VM and configured as a Samba Active Directory (AD) Domain Controller (DC).

With such an Samba AD DC, the user name is preceded by the name of the NT DOMAIN, separated by a ESC ("\\").

As an example: A login of the domain user 'johndoe' on the Samba AD DC results in the user name 'EXAMPLE\\johndoe' in [pam_yubico.c:1018](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L1018). (Note: This behavior does not occur on Samba Domain Members with the option "winbind use default domain = yes". However, this option is not available on a Samba AD DC.)

Due to the lack of implementation of the "\<valueencoding\> rule" and the occurrence of the ESC ("\\") in the user name that has been read out, it is no longer possible to log on to the Samba AD DC because the LDAP search fails. 

# Possible solution

The following instructions are inserted between [pam_yubico.c:391](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L391) and [pam_yubico.c:393](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L393):

- create a copy of the variable user, because manipulation can lead to errors in other places.

- apply a helper function to the copy of the user name, which implements the "\<valueencoding\> rule" by manipulate the copy of the user name (Call-By-Reference).

Then pass the final copy of the username instead of the read out username in [pam_yubico.c:394](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L394). 

# Hint

In [pam_yubico.c:358](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L358) the variable user is also used to generate the base DN.

It should be examined if errors can also occur in [pam_yubico.c:358](https://github.com/Yubico/yubico-pam/blob/2.27/pam_yubico.c#L358). 

This should be done in a further change request.

**Comment by DennisHeeg** [comment]
I want to give you an update to this issue. But first of all I want to say that I am new to GitHub so maybe I will need your help to create a pull request (hope this is the correct term).

I developed a solution for this issue, but i need to test it on a linux machine. All my linux systems are productive systems so I can not hunt for errors on this machines. My tests outside of the PAM Module are ok so I want to integrate my functions into your source code.

**Comment by klali** [comment]
A simple way to work when you want to make a pull-request on github is to use the fork button in the top right to create a copy of this repository. You can then push your commits on a branch there, and when you're happy with it use the pull-request button to create a pull-request on this repository from your own.

**Comment by DennisHeeg** [comment]
Thank you very much for this hint! I created a fork.

`apt install libpam-dev libyubikey-dev libykclient-dev autoconf automake libtool asciidoc xsltproc docbook-xsl libldap-dev `
`autoreconf --install`

Both run well, but when I run `./configure` I get this errors:

`./configure: line 9423: syntax error near unexpected token 'MYSQL,'`
`./configure: line 9423: '    PKG_CHECK_MODULES(MYSQL, mysqlclient,'`

I think I am missing some mysql libraries. Can u give me a hint which one i need to install?

**Comment by DennisHeeg** [comment]
I tested my changes and uploaded them as pull request #225.

**Comment by 7ippy** [comment]
Thank you for this very good collaboration! I am marking this issue as resolved. Stay healthy!
