### ISSUE TITLE
Multiple keys per user

### ISSUE THREAD

**Issue by twz123** [Yubico/yubico-pam#241]
I'd like to be able to use multiple keys to authenticate (i.e. have a backup key in case one gets lost / breaks). The [documentation](https://developers.yubico.com/yubico-pam/#_individual_authorization_mapping_by_user) mentions that a user's mapping file must have only one line. I verified that putting a second line in there makes authentication impossible with either key.

Would it be possible to add multi-key support? Are there any other workarounds for recovery?

**Comment by mrclschstr** [comment]
Use the scheme like mentioned in the docs: `<user name>:<YubiKey token ID1>:<YubiKey token ID2>`

One line per user and separate the Yubikey IDs with a colon.

**Comment by twz123** [comment]
Oh gosh. Reading the manual and _really_ reading the manual seem to be two distinct things for me. Thanks for pointing out and sorry for the noise.
