### ISSUE TITLE
verbose_otp doesn't work with ssh

### ISSUE THREAD

**Issue by klali** [Yubico/yubico-pam#25]
original issue: http://code.google.com/p/yubico-pam/issues/detail?id=51

What steps will reproduce the problem?
1. add verbose_otp as option to pam_yubico.so in the pam sshd config file.
2. try to authenticate via ssh

What is the expected output?
OK, you are logged

What do you see instead?
Not logged.
In the debug ouptut of pam_yubico.so :
  [pam_yubico.c:parse_cfg(769)] mode=client
  [pam_yubico.c:parse_cfg(770)] chalresp_path=(null)
  [pam_yubico.c:pam_sm_authenticate(810)] get user returned: max
  [pam_yubico.c:pam_sm_authenticate(906)] conv returned error: Conversation error
  [pam_yubico.c:pam_sm_authenticate(1013)] done. [Conversation error]

What version of the product are you using?
2.13

On what operating system?
Gentoo

Additional information :
I don't know if it's a bug in pam_yubico or sshd can't display "custom fields".

If sshd just can't display "custom fields" I think it should be indicated in the README file.

**Comment by steverweber** [comment]
same issue on ubuntu
```
[../pam_yubico.c:pam_sm_authenticate(808)] pam_yubico version: 2.20
[../pam_yubico.c:pam_sm_authenticate(823)] get user returned: root
[../pam_yubico.c:pam_sm_authenticate(960)] conv returned error: Conversation error
[../pam_yubico.c:pam_sm_authenticate(1095)] done. [Conversation error]
```

**Comment by klali** [comment]
It seems like it's not supported to use PAM_PROMPT_ECHO_ON with openssh in password mode (see http://lists.mindrot.org/pipermail/openssh-unix-dev/2009-September/027840.html). Will add something like this to the documentation.
