### ISSUE TITLE
challenge/response broken

### ISSUE THREAD

**Issue by eworm-de** [Yubico/yubico-pam#50]
Commit 057c3743c98aba7ae20cf44e2309d280600fa30d (fixup a memory leak) breakes challenge/response. Debug output gives:

    could not drop privileges

**Comment by klali** [comment]
actually it seems this was broken with the build changes introduced in 68d3f5879ec6782742d68d7e74066da739a0b444

the check for pam_modutil_drop_priv() was broken when -lpam wasn't added to LIBS but kept in it's own variable..

**Comment by eworm-de** [comment]
Looks good! Not sure why I blamed the wrong commit, though...
Thanks a lot!

Are we going to have tests for challenge/response as well?

**Comment by klali** [comment]
If/when I can figure out how to hit those codepaths in a testable way.. might be doable to mock the ykpers API..
