### ISSUE TITLE
Possible incompatibility with the NEO's smartcard functionality on Debian Jessie

### ISSUE THREAD

**Issue by emilecantin** [Yubico/yubico-pam#52]
I have a Yubikey NEO configured for challenge-response in the first slot, that I also use as a smartcard with GnuPG.

When using yubico-pam in challenge-response mode on Debian Jessie, GnuPG seemingly cannot access the smartcard on the Yubikey (gpg --card-status shows the card with empty key slots, and then cannot find it). The problem went away after disabling yubico-pam.

If you need more information, I would be happy to provide it.

**Comment by crosser** [comment]
My hypothesis is that your PAM module and gnupg are trying to use separate independent PC/SC backends, and they end up competing for the USB device. I run pcsclite, and both gnupg and [PAM module](https://www.average.org/chal-resp-auth/) use that.

**Comment by emilecantin** [comment]
I run whatever is installed when I "apt-get install gpg2 libpam-yubico". I'll check tonight exactly what that is. It does seem like there are two things competing for the Yubikey, so you may be onto something.

**Comment by klali** [comment]
I don't have any straight answers on what's going wrong, but I can try to explain what should happen from the Neos standpoint and what things might be interesting to look at.
To make matters worse the exact behaviour has shifted a bit with firmware versions, what I describe below is true for 3.3.1 and later.

When the Neo (in composite mode) gets a request for challenge-response (or u2f, or a button-press OTP) the Neo tells the host that the card is ejected from the reader. Then doing the challenge-response stuff and after that telling the host that the card is back.
Ideally this works without a hitch and all software is happy with the card being ejected and then showing up again.
Interesting things to look at in this case is a debug log from scdaemon for gnupg and a debug log for pcscd, if either of them show an error at this.

/klas

**Comment by emilecantin** [comment]
I don't use yubico-pam anymore, so I'll go ahead and close the issue.
