### ISSUE TITLE
Change install instructions on yubico https://developers.yubico.com/yubico-pam/

### ISSUE THREAD

**Issue by erikthorselius** [Yubico/yubico-pam#54]
On the install guide on https://developers.yubico.com/yubico-pam/ it says 

```
$ git clone git@github.com:Yubico/yubico-pam.git yubico-pam
```

Isn't it better with
```
$ git clone https://github.com/Yubico/yubico-pam.git
```
then there is no need to have access to github ssh keys. In my case I wantet to build it on a server.

**Comment by klali** [comment]
Good point. thanks!

**Comment by BillyParadise** [comment]
There is still a colon in the url on the website.
