### ISSUE TITLE
Oracle Linux 7 - configure: error: Libyubikey v1.5+ not found,

### ISSUE THREAD

**Issue by BillyParadise** [Yubico/yubico-pam#57]
I have installed the c client per instructions at 
https://developers.yubico.com/yubico-c-client/

autoreconf
configure
make check
make install

but when I go to configure the yubico-pam I get an error that Libyubikey not found.  Is there a flag I can set in the configure script to force the location?

The system recognizes a call to ykclient.

Thanks

**Comment by klali** [comment]
libyubikey refers to the project yubico-c which can be found at https://developers.yubico.com/yubico-c/ you can use --with-libyubikey-prefix=DIR to point to the installation prefix (or --with-libykclient-prefix to search for yubico-c-client)

Hope this helps!

**Comment by BillyParadise** [comment]
Thanks, will give it a go!

**Comment by klali** [comment]
I'm closing this, if the problem persist, please re-open it.

/klas

**Comment by BillyParadise** [comment]
still a problem.. gave up, moved to centos, worked great.
