### ISSUE TITLE
configure fails on OmniOS (a distribution of Illumos)

### ISSUE THREAD

**Issue by maverickbna** [Yubico/yubico-pam#58]
I am trying to run the configure script on OmniOS, which is a distribution of Illumos. For those who are not aware, Illumos is a continuation of the project formerly known as OpenSolaris.

After it reaches the stage of locating libyubikey, it errors out, saying an open parenthesis is unexpected.

Here is a pastebin of the whole configure script, and the error.

http://pastebin.com/tLkrbNF5

I get the same error if I try to add the --without-cr flag, thinking it might have to do with me not being able to install the yubikey-personalization module.

I can bypass the error if I comment out the whole code block regarding ykpers, but I'll error out the make process, when it looks for YKPERS_CFLAGS.

I have successfully compiled and installed yubico-c and yubico-c-client.

Assistance would be appreciated. Please let me know if you need any more information.

-bash-4.2$ uname -a
SunOS ip-10-180-222-32 5.11 omnios-6de5e81 i86pc i386 i86xpv
-bash-4.2$ cat /etc/release
  OmniOS v11 r151008
  Copyright 2013 OmniTI Computer Consulting, Inc. All rights reserved.
  Use is subject to license terms.

**Comment by klali** [comment]
Is this with the released yubico-pam 2.18 or from git HEAD?
Is it with the shipped configure script or did you run autoconf/automake yourself?

**Comment by maverickbna** [comment]
This is from git HEAD, after running autoreconf --install myself.

" 'With the first link, the chain is forged. The first speech censured, the
first thought forbidden, the first freedom denied, chains us all
irrevocably.' Those words were uttered by Judge Aaron Satie as wisdom and
warning... The first time any man's freedom is trodden on, we’re all
damaged." - Jean-Luc Picard, quoting Judge Aaron Satie, Star Trek: TNG
episode "The Drumhead"
- Alex Smith
- Huntsville, Alabama metropolitan area USA

**Comment by klali** [comment]
So what behaviour do you get with the 2.18 release and the configure script shipped in that?

If that errors for you please create a new paste/gist with the content.

**Comment by klali** [comment]
I'm closing this, if the problem persist, please re-open it.

/klas
