### ISSUE TITLE
yubico_pam not available in EPEL 7

### ISSUE THREAD

**Issue by Spindel** [Yubico/yubico-pam#59]
Since packages are always a lot nicer than compiling for source, I went looking for packages to enable Yubikeys in CentOS7 (and RHEL7)

it seems that the EPEL maintainers have dropped pam_yubico.  Is this something you can look at, or should we go upstream?

**Comment by klali** [comment]
To be honest I have no idea where to go for centos/rhel packages. My understanding is that the fedora package is in relatively good shape.
https://bugzilla.redhat.com/show_bug.cgi?id=1144567 seems to be a bug about inclusion in epel, that's probably the correct forum for this.
