### ISSUE TITLE
Segfault /bin/login with pam_yubico on Ubuntu 15.04

### ISSUE THREAD

**Issue by markfaine** [Yubico/yubico-pam#62]
I've tried every way I can think of to make this work, but when I attempt to add the line configured as from the example to common-auth directly after pam_unix.so it causes /bin/login to crash and I'm dropped right back to the login prompt.

auth  [success=1 default=ignore]  pam_unix.so nullok_secure
auth sufficient pam_yubico.so id=[My ID] authfile=/etc/yubikey_mappings

It works fine for lightdm, and screensavers, only login has the problem.

**Comment by klali** [comment]
This sounds like it could be a duplicate of #31 to me. There have been some workarounds suggested:

* Run nscd to cache dns replies
* Use only 1 YubiCloud server for example: urllist=https://api.yubico.com/wsapi/2.0/verify (this makes that server a single point of failure for your authentication which is a bad idea)
