### ISSUE TITLE
Issue to pass util_test

### ISSUE THREAD

**Issue by benoitne** [Yubico/yubico-pam#64]
Hi Yubico :-)

I am been using the key for a long time on debian / ubuntu systems and I am moving now to ArchLinux.
I am trying to install yubico-pam using the git version, I installed all dependencies but I am failing on the last stage ..
I tried to use --without-ldap when running ./configure as I don't need it but it keeps failing when make check install
If anyone has an idea I would appreciate a lot :)

This is the test-suite.log

   pam_yubico 2.20: tests/test-suite.log

TOTAL: 3
PASS:  2
SKIP:  0
XFAIL: 0
FAIL:  1
XPASS: 0
ERROR: 0

.. contents:: :depth: 2

FAIL: pam_test

YKVAL mockup started on 30559 at ./aux/ykval.pl line 52.
YKVAL mockup started on 17502 at ./aux/ykval.pl line 52.
[pam_yubico.c:parse_cfg(729)] called.
[pam_yubico.c:parse_cfg(730)] flags 0 argc 4
[pam_yubico.c:parse_cfg(732)] argv[0]=id=1
[pam_yubico.c:parse_cfg(732)] argv[1]=url=http://localhost:17502/wsapi/2/verify?id=%d&otp=%s
[pam_yubico.c:parse_cfg(732)] argv[2]=authfile=./aux/authfile
[pam_yubico.c:parse_cfg(732)] argv[3]=debug
[pam_yubico.c:parse_cfg(733)] id=1
[pam_yubico.c:parse_cfg(734)] key=(null)
[pam_yubico.c:parse_cfg(735)] debug=1
[pam_yubico.c:parse_cfg(736)] alwaysok=0
[pam_yubico.c:parse_cfg(737)] verbose_otp=0
[pam_yubico.c:parse_cfg(738)] try_first_pass=0
[pam_yubico.c:parse_cfg(739)] use_first_pass=0
[pam_yubico.c:parse_cfg(740)] authfile=./aux/authfile
[pam_yubico.c:parse_cfg(741)] ldapserver=(null)
[pam_yubico.c:parse_cfg(742)] ldap_uri=(null)
[pam_yubico.c:parse_cfg(743)] ldap_bind_user=(null)
[pam_yubico.c:parse_cfg(744)] ldap_bind_password=(null)
[pam_yubico.c:parse_cfg(745)] ldap_filter=(null)
[pam_yubico.c:parse_cfg(746)] ldap_cacertfile=(null)
[pam_yubico.c:parse_cfg(747)] ldapdn=(null)
[pam_yubico.c:parse_cfg(748)] user_attr=(null)
[pam_yubico.c:parse_cfg(749)] yubi_attr=(null)
[pam_yubico.c:parse_cfg(750)] yubi_attr_prefix=(null)
[pam_yubico.c:parse_cfg(751)] url=http://localhost:17502/wsapi/2/verify?id=%d&otp=%s
[pam_yubico.c:parse_cfg(752)] urllist=(null)
[pam_yubico.c:parse_cfg(753)] capath=(null)
[pam_yubico.c:parse_cfg(754)] token_id_length=12
[pam_yubico.c:parse_cfg(755)] mode=client
[pam_yubico.c:parse_cfg(756)] chalresp_path=(null)
[pam_yubico.c:pam_sm_authenticate(787)] pam_yubico version: 2.20
in pam_get_user()
[pam_yubico.c:pam_sm_authenticate(802)] get user returned: foo
in pam_get_item() 5
in conv_func()
[pam_yubico.c:pam_sm_authenticate(949)] conv returned 44 bytes
[pam_yubico.c:pam_sm_authenticate(967)] Skipping first 0 bytes. Length is 44, token_id set to 12 and token OTP always 32.
[pam_yubico.c:pam_sm_authenticate(974)] OTP: vvincredibletrerdegkkrkkneieultcjdghrejjbckh ID: vvincredible
[pam_yubico.c:pam_sm_authenticate(1004)] ykclient return value (109): Error performing curl
[pam_yubico.c:pam_sm_authenticate(1005)] ykclient url used:
[pam_yubico.c:pam_sm_authenticate(1073)] in pam_strerror()
done. [error]
in pam_set_data() yubico_setcred_return
test 1 failed!
killed 13963 and 13964
FAIL pam_test (exit status: 1)

Many thanks,

Belette

**Comment by benoitne** [comment]
Auto reply -> iptables was the gulty! and the test was block by some rule

**Comment by klali** [comment]
Good to hear that you solved it.

/klas
