### ISSUE TITLE
Release File Names

### ISSUE THREAD

**Issue by systmkor** [Yubico/yubico-pam#66]
Is there a particular reason that releases for **yubico-pam** just have the version name instead of `yubico-pame-<version>.tar.gz`? This is inconsistent with other Yubico projects such as for **libykneomgr** which has `libykneomgr-<version>.tar.gz`. Without out manual renaming this can cause name collisions for package builders that maintain a cache of source code releases.

**Comment by klali** [comment]
Hello,

The real releases of this project can be found at https://developers.yubico.com/yubico-pam/Releases/ with good names. The releases tab on github shows things they came up with and we're still deciding how to handle that.

/klas
