### ISSUE TITLE
Yubico Authorization Plugin for OS X

### ISSUE THREAD

**Issue by tburgin** [Yubico/yubico-pam#75]
Do you have any plans to build an Authorization Plugin for OS X?
This would allow a for a richer UI experience.

https://developer.apple.com/library/mac/documentation/Security/Reference/AuthorizationPluginRef/index.html
https://developer.apple.com/library/mac/technotes/tn2228/_index.html

**Comment by klali** [comment]
There are no current plans to build that.

Further: if we where to build it I'm unsure if it would make sense to build it as part of the pam module, to me it sounds more like it's own project.

Thank you for the resources!

**Comment by tburgin** [comment]
Sounds good, thanks.
