### ISSUE TITLE
yclient 107 BAD_SERVER_SIGNATURE

### ISSUE THREAD

**Issue by schlutech** [Yubico/yubico-pam#91]
I am running Ubuntu 14.04 (Trusty) and using the prescribed repository such that:

> libpam-yubico:
>   Installed: 2.21-1~ppa1~trusty1

When using YubiCloud servers everything works perfectly. When I change to use any internal servers such as:

`auth required pam_yubico.so mode=client id=1 key=rcxoDqVSsPeev/LjhnnQGBnrWk0= urllist=https://127.0.0.1/wsapi/2.0/verify`

this always returns "BAD_SERVER_SIGNATURE"

When I try to troubleshoot using yclient:

> libykclient-dev:
>   Installed: 2.15-1~ppa1~trusty1

I get Verification output (107): Server response signature was invalid (BAD_SERVER_SIGNATURE) though the status field returns correctly (OK, REPLAYED_OTP, etc.)

**Comment by klali** [comment]
So this is the verification of the servers reply that's failing. Are you running the yubikey-val server as your validation server? It might be useful to capture debug level output from that.

**Comment by schlutech** [comment]
This is happening on the Go validation server referenced here:

https://developers.yubico.com/Software_Projects/YubiKey_OTP/YubiCloud_Validation_Servers/
https://github.com/digintLab/yubikey-server

As well as the latest version of yubiserver in the Ubuntu Trusty repository (0.4-3) plus the latest compiled version of yubiserver (0.6) found here:

http://yubiserver.include.gr/

**Comment by schlutech** [comment]
Well the yubikey-val and yubikey-ksm packages in the Ubuntu Trusty (14.04) : 

> yubikey-val:
 >Installed: 2.33-1~ppa1~trusty1

>yubikey-ksm:
>Installed: 1.14-2~ppa1~trusty1

Works without issue. But I find it odd that one of the validation servers listed on Yubiko's site as well as another validation server not listed on the site but suffer the same issue though they are separate projects with separate programming languages and code-bases.

I did therefore test out this validation server:

https://github.com/scumjr/yubikeyedup

Also referenced on the same page:

https://developers.yubico.com/Software_Projects/YubiKey_OTP/YubiCloud_Validation_Servers/

It too works as expected. I suppose 2/4 means I should file bug reports with the other validation server developers?

**Comment by klali** [comment]
Yes, to me that seems like an issue in those validation servers. The list on developers.yubico.com is not a carefully curated list, more pointers to alternatives.

**Comment by klali** [comment]
Closing this since I don't believe it to be an issue with yubico-pam.
