### ISSUE TITLE
[Bug] Issue using challenge-response on Ubuntu 16.04

### ISSUE THREAD

**Issue by Dschubba** [Yubico/yubico-pam#99]
Hi,

I've got a problem with the files that are written for the challenge-response via the pam-yubico using challenge-response.

My home partition is encrypted, thus I've got a different directory for the challenge-response files as described in https://developers.yubico.com/yubico-pam/Authentication_Using_Challenge-Response.html

I created first the file with  and the permissions and the user as described:

`$ ykpamcfg -2 -v -p /var/yubico`

The initial written file has the correct permissions in the directory and belongs to my user that created this file.

However after I log in after a reboot, or user "Switch user" functionality in the upper left corner, the file changes the permissions to `-rw-------` (which should be ok) and - this is the problem - does a `chown` to `root` user and the `root` group.

This is a problem, because I cant unlock my computer as a normal user from the lock screen (the debug log of pam-yubico says "Unable to read file ...", it tries to read it as a non-root user), so I need to use the "Switch User" functionality to unlock my computer.

Could you please advise - is this a bug in Ubuntu, or is this here the right place for the bug report?

Thank you!

**Comment by klali** [comment]
You're correct, this is a bug in the module. It was previously reported as #92 and fixed with 155b485ba7d659b3c6992b9bdf8c067369990677

I'll make a release that includes this shortly.

**Comment by Joeviocoe** [comment]
Is there a workaround for this?  Or am I expected to recompile with this commit [155b485](https://github.com/Yubico/yubico-pam/commit/155b485ba7d659b3c6992b9bdf8c067369990677)?

Kubuntu has this issue when using the shared /var/yubico directory per the instructions.  Linux Mint seems unaffected using the same configuration.

**Comment by klali** [comment]
That commit is included from release 2.23, so if you run that or later it is included. There is a ppa repository at https://launchpad.net/~yubico/+archive/ubuntu/stable containing builds of the latest releases for ubuntu.

**Comment by 1989gironimo** [comment]
I have pretty much the same problem on Ubuntu 17.04 and the newest pam module from the ppa yubico provides.
My auth file for c/r is in /var/yubikey with root.root as user/group with the appropriate permission 600 because of an encrypted homedirectory
